import "./globals.css";

import AppHeader from "@/components/AppHeader";
import AppFooter from "@/components/AppFooter";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const fetchCache = "force-no-store";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-col items-center justify-between">
        <AppHeader />
        {children}
        <AppFooter />
      </body>
    </html>
  );
}
